### ISSUE TITLE
Does not show the cost of custom cards

### ISSUE THREAD

**Issue by Paradox75831004** [Gloveman23/MoonPriceDisplay#1]
Custom maps from LethalLevelLoader and LethalExpansion, Lethal Expansion Core do not display the value of moons (check the cost config change, it should take this into account too)
![image](https://github.com/Gloveman23/MoonPriceDisplay/assets/72872478/c12ff0b5-bccc-4e2e-9ce2-27f9dddc4f27)

**Comment by dragonmcmx1** [comment]
To add to this, it seems to me that if LethalLevelLoader is installed, this mod does not work at all, even on the vanilla moons.

**Comment by Gloveman23** [comment]
Modded moons should now show prices as intended. LethalLevelLoader has its own options for showing price, so if you have that mod you should use it instead.

**Comment by Blastinburn** [comment]
> LethalLevelLoader has its own options for showing price, so if you have that mod you should use it instead.

LethalLevelLoader doesn't generate a config and has no options in-game so I don't know where there could possibly be an option to show moon prices with that mod.

LethalExpansion has an option to show moon prices, but LethalExpansion is also a sprawling mess of way too much stuff crammed into a single mod and doesn't work with other moon/interior loaders unless you override it last I checked..

**Comment by dragonmcmx1** [comment]
I think LethalLevelLoader has an update coming very soon with that and more features.
